
#Layout of the players's name before his message (only works if you have PlaceHolderAPI).
namedisplay: "%townyadvanced_towny_tag_override% %player_displayname%"



#=================================================================================
# Advanced Section. Don't touch this if you don't know what you are doing.
# Trust me you might end up without chat or other functions on all your servers.
#=================================================================================

communicationChannel: "crosschat:message"