name: CrossChat
version: 1.1.0
description: Sender plugin to chat across multiple Bungee/Waterfall servers.

author: _Matai_
# website: http://forums.bukkit.org/threads/MyPlugin.31337/

main: ca.matai.CrossChat.CrossChatSpigot
database: false

