name: CrossChat
version: 1.0.1
description: Plugin to chat across multiple Bungee/Waterfall servers.

author: _Matai_
# website: http://forums.bukkit.org/threads/MyPlugin.31337/

main: ca.matai.CrossChat.CrossChatSpigot
database: false

#depend: [NewFire, FlameWire]

#commands:
#  flagrate:
#    description: Set yourself on fire.
#    aliases: [combust_me, combustMe]
#    permission: inferno.flagrate
#    usage: Syntax error! Simply type /&lt;command&gt; to ignite yourself.
#  burningdeaths:
#    description: List how many times you have died by fire.
#    aliases: [burning_deaths, burningDeaths]
#    permission: inferno.burningdeaths
#    usage: |
#      /&lt;command&gt; [player]
#      Example: /&lt;command&gt; - see how many times you have burned to death
#      Example: /&lt;command&gt; CaptainIce - see how many times CaptainIce has burned to death
#
#permissions:
#  inferno.*:
#    description: Gives access to all Inferno commands
#    children:
#      inferno.flagrate: true
#      inferno.burningdeaths: true
#      inferno.burningdeaths.others: true
#  inferno.flagrate:
#    description: Allows you to ignite yourself
#    default: true
#  inferno.burningdeaths:
#    description: Allows you to see how many times you have burned to death
#    default: true
#  inferno.burningdeaths.others:
#    description: Allows you to see how many times others have burned to death
#    default: op
#    children:
#      inferno.burningdeaths: true