name: CrossChat
version: 1.2.0
description: Receiver plugin to chat across multiple Bungee/Waterfall servers.


author: _Matai_
# website: http://forums.bukkit.org/threads/MyPlugin.31337/

main: ca.matai.crosschat.CrossChatBungee
database: false